Rust: Updated send-email.rs for Contact list with more that one contact, SES (#5202)
* Update send-email.rs

cs is being returned without a comma. eg:
user@example.comuser2@example.com...
Causes Exception:
Error: BadRequestException(BadRequestException { message: Some("Illegal address"), meta: ErrorMetadata { code: Some("BadRequestException"), message: Some("Illegal address"), extras: Some({"aws_request_id": "da0bf20a-52b3-4acc-bb22-eec27cf68322"}) } })

If the contact list has more that one contact it will fail.

* Update send-email.rs - Fixed for Contact List with more that one

Fixed.
cs is being generated as String, if the Contact list has more that one contact it will fail. eg:
user@example.comuser2@example.com...
Causes Exception:
Error: BadRequestException(BadRequestException { message: Some("Illegal address"), meta: ErrorMetadata { code: Some("BadRequestException"), message: Some("Illegal address"), extras: Some({"aws_request_id": "da0bf20a-52b3-4acc-bb22-eec27cf68322"}) } })

cs is now a Vec<String> and is directly assigned to dest.to_addresses

* Update send-email.rs

rustfmt

---------

Co-authored-by: David Souther <davidsouther+github@gmail.com>